// Centralized FontAwesome icons
import {
  faArrowDown,
  faArrowUp,
  faBookmark,
  faCheck,
  faCheckCircle,
  faCircleNotch,
  faClock,
  faCloudArrowDown,
  faCompass,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faMagnifyingGlass,
  faMusic,
  faPause,
  faPlay,
  faRepeat,
  faRightFromBracket,
  faShuffle,
  faStepBackward,
  faStepForward,
  faTimes,
  faTrash,
  faTriangleExclamation,
  faWaveSquare,
  faXmark,
  IconDefinition,
} from '@fortawesome/free-solid-svg-icons';

import { faHeart as faHeartRegular } from '@fortawesome/free-regular-svg-icons';
import { faHeart as faHeartSolid } from '@fortawesome/free-solid-svg-icons';

export {
  IconDefinition,
  // Solid icons
  faArrowDown,
  faArrowUp,
  faBookmark,
  faCheck,
  faCheckCircle,
  faCircleNotch,
  faClock,
  faCloudArrowDown,
  faCompass,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faMagnifyingGlass,
  faMusic,
  faPause,
  faPlay,
  faRepeat,
  faRightFromBracket,
  faShuffle,
  faStepBackward,
  faStepForward,
  faTimes,
  faTrash,
  faTriangleExclamation,
  faWaveSquare,
  faXmark,
  // Heart icons (aliased)
  faHeartRegular,
  faHeartSolid,
};
